# -*- coding: utf-8 -*-
"""testeCluster.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QqF4-sB3EoQvD7PmsmHr_Dl_hZFf8U-L
"""

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
from selenium.common.exceptions import NoSuchElementException, TimeoutException
import time
import os
import requests

url_rodada = "https://api.cartolafc.globo.com/mercado/status"
texto_rodada = requests.get(url_rodada).text
rodada = int(texto_rodada.split('{"rodada_atual":')[1].split(',"status_mercado":')[0])

 
directory = f"source_rdd_{rodada-1}"
parent_dir = "C:/Users/Breno Valente/Desktop/Cartola/sofascore_source"
path = os.path.join(parent_dir, directory)  
os.mkdir(path) 



links = [
'https://www.sofascore.com/team/football/bahia/1955',
'https://www.sofascore.com/team/football/red-bull-bragantino/1999',
'https://www.sofascore.com/team/football/ceara-sc/2001',
'https://www.sofascore.com/team/football/fortaleza/2020',
'https://www.sofascore.com/team/football/atletico-goianiense/7314',
'https://www.sofascore.com/team/football/athletico-paranaense/1967',
'https://www.sofascore.com/team/football/flamengo/5981',
'https://www.sofascore.com/team/football/cuiaba/49202',
'https://www.sofascore.com/team/football/juventude/1980',
'https://www.sofascore.com/team/football/internacional/1966',
'https://www.sofascore.com/team/football/sport-recife/1959',
'https://www.sofascore.com/team/football/fluminense/1961',
'https://www.sofascore.com/team/football/sao-paulo/1981',
'https://www.sofascore.com/team/football/gremio/5926',
'https://www.sofascore.com/team/football/atletico-mineiro/1977',
'https://www.sofascore.com/team/football/america-mineiro/1973',
'https://www.sofascore.com/team/football/corinthians/1957',
'https://www.sofascore.com/team/football/palmeiras/1963',
'https://www.sofascore.com/team/football/chapecoense/21845',
'https://www.sofascore.com/team/football/santos/1968'
]

times = ['BAH', 'BGT', 'CEA', 'FOR', 'ACG', 'CAP', 'FLA', 'CUI', 'JUV', 'INT', 'SPT', 'FLU', 'SAO', 'GRE', 'CAM',
'AME', 'COR', 'PAL', 'CHA', 'SAN']
condicao = True
while condicao == True: 
  try:
    binary = FirefoxBinary('C:\\Program Files\\Mozilla Firefox\\firefox.exe')
    driver = webdriver.Firefox(firefox_binary=binary, executable_path=r'C:\\geckodriver.exe')
    time.sleep(3)
    driver.get("https://www.google.com/")
    condicao = False

  except TimeoutException:
    driver.close()
    contador += 1
    print(f"{contador}ª tentativa")
    time.sleep(5)

for i, clube in enumerate(links):
  driver.get(clube)
  time.sleep(10)

  f = open(f'sofascore_source/source_rdd_{rodada-1}/{times[i]}.txt','x', encoding="utf-8")
  f.write(driver.page_source)
  f.close()

time.sleep(5)
driver.close()



