# -*- coding: utf-8 -*-
"""main_BrenoMestre.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cHnoC2Ep0vGN1jHRY7W0g6Rqs_ON73Me
"""


import json
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup
import wikipedia
import os
import time

url_rodada = "https://api.cartolafc.globo.com/mercado/status"
texto_rodada = requests.get(url_rodada).text
rodada = int(texto_rodada.split('{"rodada_atual":')[1].split(',"status_mercado":')[0])

url_mercado = "https://api.cartolafc.globo.com/atletas/mercado"
texto_mercado = requests.get(url_mercado).text


url_partidas = "https://api.cartolafc.globo.com/partidas"
texto_partidas = requests.get(url_partidas).text

url_rodada_passada = f"https://api.cartolafc.globo.com/partidas/{rodada-1}"
texto_rodada_passada = requests.get(url_rodada_passada).text

#criando txt com os textos extraídos anteriormente para que o json.load(.json) funcione
if os.path.exists(f'dados_api/mercado{rodada-1}.txt'):
  os.remove(f'dados_api/mercado{rodada-1}.txt')
f = open(f'dados_api/mercado{rodada-1}.txt', mode='x', encoding = 'utf-8')
f.write(texto_mercado)
f.close()

if os.path.exists(f'dados_api/partidas{rodada}.txt'):
  os.remove(f'dados_api/partidas{rodada}.txt')
f = open(f'dados_api/partidas{rodada}.txt', mode='x', encoding = 'utf-8')
f.write(texto_partidas)
f.close()

if os.path.exists(f'dados_api/rodada{rodada-1}.txt'):
  os.remove(f'dados_api/rodada{rodada-1}.txt')
f = open(f'dados_api/rodada{rodada-1}.txt', mode='x', encoding = 'utf-8')
f.write(texto_rodada_passada)
f.close()

json_mercado = json.load(open(f'dados_api/mercado{rodada-1}.txt', encoding = 'utf-8'))
json_partida = json.load(open(f'dados_api/partidas{rodada}.txt', encoding = 'utf-8'))
json_rodada = json.load(open(f'dados_api/rodada{rodada-1}.txt', encoding = 'utf-8'))

dict_aux = { '7': {'abreviacao': 'LD', 'id': 7, 'nome': 'Lateral Direito'}, '8': {'abreviacao': 'LE', 'id': 8, 'nome': 'Lateral Esquerda'}}
json_mercado['posicoes'].update(dict_aux)


df_proxima_partida = pd.DataFrame.from_dict(json_partida['partidas']).drop(['partida_data', 'timestamp', 'local', 'placar_oficial_mandante', 'placar_oficial_visitante', 'status_transmissao_tr', 'inicio_cronometro_tr', 'status_cronometro_tr', 'periodo_tr', 'transmissao'], axis = 1)
df_rodada_jogada = pd.DataFrame.from_dict(json_rodada['partidas']).drop(['partida_data', 'timestamp', 'local', 'status_transmissao_tr', 'inicio_cronometro_tr', 'status_cronometro_tr', 'periodo_tr', 'transmissao'], axis = 1)

def calcula_aproveitamento(list_aproveitamento):
  aproveitamento = (list_aproveitamento.count('e')*1+list_aproveitamento.count('v')*3)/((list_aproveitamento.count('e')+list_aproveitamento.count('v')+list_aproveitamento.count('d'))*3)
  return round(aproveitamento, 2)


df_proxima_partida['aproveitamento_mandante'] = df_proxima_partida['aproveitamento_mandante'].apply(lambda x: calcula_aproveitamento(x))
df_proxima_partida['aproveitamento_visitante'] = df_proxima_partida['aproveitamento_visitante'].apply(lambda x: calcula_aproveitamento(x))

df_rodada_jogada['aproveitamento_mandante'] = df_rodada_jogada['aproveitamento_mandante'].apply(lambda x: calcula_aproveitamento(x))
df_rodada_jogada['aproveitamento_visitante'] = df_rodada_jogada['aproveitamento_visitante'].apply(lambda x: calcula_aproveitamento(x))


def cria_dict_scouts(scout):
  """
  Função para criar um dicionário com os scouts do jogador
  
  Argumento: Dicionário com os scouts
  Saída: Dicionário com todos os scouts. Se o jogador não tem determinado scout, a função define como 0
  """
  siglas_scout = ['G', 'A', 'FT', 'FD', 'FF', 'FS', 'PP', 'I', 'PI', 'PS', 'SG', 'DP', 'DE', 'DS', 'GC', 'CV', 'CA', 'GS', 'FC', 'PC']
  new_dict = {}
  for siglas in siglas_scout:
    
    if atleta['scout'] is None:
      new_dict.update({siglas:0})

    else:
      if siglas not in scout.keys():
        new_dict.update({siglas:0})
      else:
        new_dict.update({siglas:scout[siglas]})
  return new_dict

dicionario_mercado = json_mercado['atletas']

for atleta in dicionario_mercado:
  scouts = cria_dict_scouts(atleta['scout'])
  atleta.update(scouts)
  atleta.pop('scout')

def inclui_clube(ID:int):
  return json_mercado['clubes'][str(ID)]['abreviacao']

def inclui_status(Status_ID:int):
  return json_mercado['status'][str(Status_ID)]['nome']

def inclui_posicao(Posicao_ID:int):
  return json_mercado['posicoes'][str(Posicao_ID)]['nome']

def inclui_mando(id_clube):
  
  if id_clube in df_rodada_jogada.clube_casa_id.unique():
    return 1
  elif id_clube in df_rodada_jogada.clube_visitante_id.unique():
    return 0 
  else:
    return np.nan

def inclui_adversario(clube_id):
  df_aux_home = df_rodada_jogada.set_index('clube_casa_id')
  df_aux_alway = df_rodada_jogada.set_index('clube_visitante_id')

  if clube_id in df_aux_home.index:
    return df_aux_home.loc[clube_id]['clube_visitante_id']
  elif clube_id in df_aux_alway.index:
    return df_aux_alway.loc[clube_id]['clube_casa_id']
  else:
    return np.nan

def inclui_mando_proxima_rodada(id_clube):
  if id_clube in df_proxima_partida.clube_casa_id.unique():
    return 1
  elif id_clube in df_proxima_partida.clube_visitante_id.unique():
    return 0 
  else:
    return np.nan

def inclui_lado(nome, posicao):
  
  if posicao != 2:
    return posicao
  else:
    try:
      informacoes_jogador = wikipedia.page(nome).content

      if 'right back' in informacoes_jogador:
        return 7
      elif 'left back' in informacoes_jogador:
        return 8
      elif 'right' in informacoes_jogador and 'left' not in informacoes_jogador:
        return 7
      elif 'left' in informacoes_jogador and 'right' not in informacoes_jogador:
        return 8
      else:
        return 2
    except wikipedia.exceptions.PageError:
      return 2
    except KeyError:
      return 2 

df_mercado = pd.DataFrame.from_dict(dicionario_mercado)

var_auxiliar_erro = True
if atleta is None:
  var_auxiliar_erro = False

if var_auxiliar_erro:
  df_mercado['posicao_id'] = df_mercado.apply(lambda x: inclui_lado(x['nome'], x['posicao_id']), axis=1)

df_mercado['Clube_nome'] = df_mercado['clube_id'].apply(lambda x: inclui_clube(x))
df_mercado['Status_nome'] = df_mercado['status_id'].apply(lambda x: inclui_status(x))
df_mercado['Posicao_nome'] = df_mercado['posicao_id'].apply(lambda x: inclui_posicao(x))
df_mercado['Mandante'] = df_mercado['clube_id'].apply(lambda x: inclui_mando(x))
df_mercado['Adversario'] = df_mercado['clube_id'].apply(lambda x: inclui_adversario(x))
df_mercado['Adversario_nome'] = df_mercado['Adversario'].apply(lambda x: inclui_clube(x))
df_mercado['Mando_clube_prox_rdd'] = df_mercado['clube_id'].apply(lambda x: inclui_mando_proxima_rodada(x))
df_mercado['Mando_adversario_prox_rdd'] = df_mercado['Adversario'].apply(lambda x: inclui_mando_proxima_rodada(x))


df_mercado.columns=['ID', 'Rodada', 'Clube_ID', 'Posicao_ID', 'Status_ID', 'Pontos', 'Preco', 'Variacao', 'Media', 'Jogos', 'Slug', 'Apelido', 'Apelido_abreviado', 'Nome', 'Foto', 'G', 'A', 'FT', 'FD', 'FF', 'FS', 'PP', 'I', 'PI', 'PS', 'SG', 'DP', 'DE', 'DS', 'GC', 'CV', 'CA', 'GS', 'FC', 'PC', 'Clube_nome', 'Status_nome', 'Posicao_nome', 'Mandante', 'Adversario', 'Adversario_nome', 'Mando_clube_prox_rdd', 'Mando_adversario_prox_rdd']
colunas = ['ID', 'Nome', 'Apelido', 'Apelido_abreviado', 'Slug', 'Foto', 'Posicao_ID', 'Posicao_nome', 'Status_ID', 'Status_nome', 'Clube_ID', 'Clube_nome', 'Adversario', 'Adversario_nome', 'Mandante', 'Rodada', 'Pontos','Mando_clube_prox_rdd','Mando_adversario_prox_rdd', 'Preco', 'Variacao', 'Media', 'Jogos', 'G', 'A', 'FT', 'FD', 'FF', 'FS', 'PP', 'I', 'PI', 'PS', 'SG', 'DP', 'DE', 'DS', 'GC', 'CV', 'CA', 'GS', 'FC', 'PC']
df_mercado = df_mercado[colunas]

df_mercado.to_excel(f"mercado_bruto/Mercado_bruto_rodada{rodada}.xlsx", index=False)
df_rodada_jogada.to_excel(f"rodadas/{rodada-1}.xlsx", index = False)

if rodada == 2:
  df_diferenca_mercado = df_mercado 


  df_bck_mercado = df_diferenca_mercado.copy()

else:
  df_mercado_rdd_anterior = pd.read_excel(f"mercado_bruto/Mercado_bruto_rodada{rodada-1}.xlsx")



  info_possiveis_mercado = ['ID', 'G', 'A', 'FT', 'FD', 'FF', 'FS', 'PP', 'I', 'PI', 'PS', 'SG', 'DP', 'DE', 'DS', 'GC', 'CV', 'CA', 'GS', 'FC', 'PC']

  df_diferenca_mercado = (df_mercado[info_possiveis_mercado].set_index("ID") - df_mercado_rdd_anterior[info_possiveis_mercado].set_index("ID")).reset_index()
  df_diferenca_mercado.dropna(inplace = True)

  coluna_adicionavel_mercado = []

  for coluna in list(df_mercado.columns): 
    if ((coluna not in info_possiveis_mercado) == True):
      coluna_adicionavel_mercado.append(coluna)



  df_bck_mercado = df_diferenca_mercado.copy()

  df_bck_mercado = df_bck_mercado.set_index("ID")

  for id in df_diferenca_mercado.ID.unique():
    for coluna in coluna_adicionavel_mercado:     
      df_bck_mercado.loc[[id], [coluna]] = df_mercado[df_mercado['ID'] == id][coluna].values[0]

  df_bck_mercado = df_bck_mercado.reset_index()
  df_bck_mercado = df_bck_mercado[df_mercado.columns]

df_bck_mercado.to_excel(f'mercado_diff/diferenca{rodada-1}.xlsx', index = None) #diferenca sofascore
df_completo_mercado = pd.read_excel("completo_mercado.xlsx")
df_aux_mercado = pd.concat([df_completo_mercado, df_bck_mercado])
df_aux_mercado.to_excel("completo_mercado.xlsx", index=None)


###########################################################################################################################
###########################                  ARRUMANDO SOFASCORE                 ##########################################
###########################################################################################################################
#sofascore
times = [('BAH',265), ('BGT',280), ('CEA',354), ('FOR',356), ('ACG',373), ('CAP',293), ('FLA',262), ('CUI',1371), ('JUV',286), ('INT',285), 
         ('SPT',292), ('FLU',266), ('SAO',276), ('GRE',284), ('CAM',282), ('AME',327), ('COR',264), ('PAL',275), ('CHA',315), ('SAN',277)]
colunas = ['Time', 'ID','Matches','Goals scored','Goals conceded', 'Assists', 'Goals per game', 'Goal conversion', 'Penalty goals', 'Free kick goals', 
           'Goals from inside the box', 'Goals from outside the box', 'Left foot goals', 'Right foot goals', 'Headed goals', 'Big chances per game', 'Big chances missed per game','Total shots per game',
           'Shots on target per game','Shots off target per game','Succ. dribbles per game','Corners per game','Hit woodwork','Counter attacks','Ball possession',
           'Accurate per game','Acc. own half','Acc. opposition half','Acc. long balls','Acc. crosses','Clean sheets','Goals conceded per game','Tackles per game',
           'Interceptions per game','Clearances per game','Saves per game','Errors leading to shot','Errors leading to goal','Penalties committed','Penalty goals conceded','Clearance off line','Last man tackle','Duels won per game','Ground duels won',
           'Aerial duels won','Possession lost per game','Offsides per game','Fouls per game','Yellow cards per game','Red cards']

lista_infos = []
for time, id in times:
  f = open(f'sofascore_source/source_rdd_{rodada-1}/{time}.txt', 'r', encoding = 'utf-8')
  soup = BeautifulSoup(f, 'html.parser')
  #informacao = soup.find_all("span", {"class": "styles__SeasonStatisticsItemValue-sc-1auya7b-8 cwFePM"}) essa era a versao antiga do site
  informacao = soup.find_all("span", {"class": "styles__SeasonStatisticsItemValue-sc-1t4e13j-8 iYAOIT"})


  
  info_time = [time, id]
  for info in informacao:
    info_time.append(info.text)
  lista_infos.append(info_time)
  f.close()



df_sofascore = pd.DataFrame.from_records(lista_infos)



df_sofascore.columns = colunas
df_sofascore.fillna(0)


def converte_para_float(x):
  return float(x)

def tira_porcentagem_limpa(x):
  """
  Função para tirar a porcentagem que está em uma linha.
  Ex: 60%, 6%, 100%
  """
  return converte_para_float(x[:-1])/100
#######################################################################
def extrai_total_acc(x):
  """
  Função para extrair o total da acao feito e a acuracia.
  Ex: Penalti goals = 0/1 -> Time chutou 1 penalti e fez 0 gols. Acc = 0%
  """
  parcelas = x.split('/')
  total = float(parcelas[1])
  return int(round(total,0))
  
def extrai_acertados_acc(x):
  """
  Função para extrair o total da acao feito e a acuracia.
  Ex: Penalti goals = 0/1 -> Time chutou 1 penalti e fez 0 gols. Acc = 0%
  """
  parcelas = x.split('/')
  
  return float(parcelas[0])

def extrai_acc_acc(x):
  """
  Função para extrair o total da acao feito e a acuracia.
  Ex: Penalti goals = 0/1 -> Time chutou 1 penalti e fez 0 gols. Acc = 0%
  """
  parcelas = x.split('/')
  total = float(parcelas[1])
  if float(parcelas[1]) != 0:
    acuracia = float(parcelas[0])/float(parcelas[1])
  else:
    acuracia = 0
  
  return round(acuracia, 2)
#######################################################
def extrai_total_porcentagem(x):
  parcelas = x.split(' (')

  acertados = float(parcelas[0])
  acuracia = round(converte_para_float(parcelas[1].split('%)')[0])/100,2)
  if acuracia != 0:
    total = float(acertados)/acuracia
  else:
    total = 0

  return int(round(total,0))
def extrai_acertados_porcentagem(x):
  parcelas = x.split(' (')

  acertados = float(parcelas[0])

  return acertados

def extrai_acc_porcentagem(x):
  parcelas = x.split(' (')

  acertados = float(parcelas[0])
  acuracia = round(converte_para_float(parcelas[1].split('%)')[0])/100,2)

  return acuracia

#colunas_para_remover = ['Matches', 'Goals scored', 'Goals conceded', 'Assists', 'Left foot goals', 'Right foot goals', 'Hit woodwork', 'Clearances per game', 'Penalties committed', 'Clearance off line']

numericas = ['Matches', 'Goals scored', 'Goals conceded', 'Assists', 'Goals per game', 'Left foot goals', 'Right foot goals', 
             'Headed goals', 'Big chances per game', 'Big chances missed per game', 'Total shots per game', 
             'Shots on target per game', 'Shots off target per game', 'Succ. dribbles per game', 'Corners per game', 
             'Hit woodwork', 'Counter attacks', 'Clean sheets', 'Goals conceded per game', 'Tackles per game', 
             'Interceptions per game', 'Clearances per game', 'Saves per game', 'Errors leading to shot', 
             'Errors leading to goal', 'Penalties committed', 'Penalty goals conceded', 'Clearance off line', 
             'Last man tackle', 'Possession lost per game', 'Offsides per game', 'Fouls per game', 'Yellow cards per game', 
             'Red cards']
porcento_inline = ['Goal conversion', 'Ball possession']

acertado_total = ['Penalty goals', 'Free kick goals', 'Goals from inside the box', 'Goals from outside the box']

porcento_acc = ['Accurate per game', 'Acc. own half', 'Acc. opposition half', 'Acc. long balls', 'Acc. crosses', 'Duels won per game', 'Ground duels won', 'Aerial duels won']



for coluna in numericas:
  df_sofascore[coluna] = df_sofascore[coluna].apply(lambda x: converte_para_float(x))
for coluna in porcento_inline:
  df_sofascore[coluna] = df_sofascore[coluna].apply(lambda x: tira_porcentagem_limpa(x))

for coluna in acertado_total:
  df_sofascore[f'{coluna}_total'] = df_sofascore[coluna].apply(lambda x: extrai_total_acc(x))
  df_sofascore[f'{coluna}_acertados'] = df_sofascore[coluna].apply(lambda x: extrai_acertados_acc(x))
  df_sofascore[f'{coluna}_acuracia'] = df_sofascore[coluna].apply(lambda x: extrai_acc_acc(x))
  df_sofascore.drop(columns=[coluna], inplace = True)
for coluna in porcento_acc:
  df_sofascore[f'{coluna}_total'] = df_sofascore[coluna].apply(lambda x: extrai_total_porcentagem(x))
  df_sofascore[f'{coluna}_acertados'] = df_sofascore[coluna].apply(lambda x: extrai_acertados_porcentagem(x)) 
  df_sofascore[f'{coluna}_acuracia'] = df_sofascore[coluna].apply(lambda x: extrai_acc_porcentagem(x))
  df_sofascore.drop(columns=[coluna], inplace = True)




df_sofascore['Mandante'] = df_sofascore['ID'].apply(lambda x: inclui_mando(x))
df_sofascore['Adversario_id'] = df_sofascore['ID'].apply(lambda x: inclui_adversario(x))
df_sofascore['Adversario_nome'] = df_sofascore['Adversario_id'].apply(lambda x: inclui_clube(x))
df_sofascore['Mando_clube_prox_rdd'] = df_sofascore['ID'].apply(lambda x: inclui_mando_proxima_rodada(x))
df_sofascore['Mando_adversario_prox_rdd'] = df_sofascore['Adversario_id'].apply(lambda x: inclui_mando_proxima_rodada(x))

df_sofascore = df_sofascore[['Time', 'ID','Adversario_nome', 'Adversario_id',
       'Mandante', 'Mando_clube_prox_rdd', 'Mando_adversario_prox_rdd', 'Matches', 'Goals scored', 'Goals conceded', 'Assists',
       'Goals per game', 'Goal conversion', 'Left foot goals',
       'Right foot goals', 'Headed goals', 'Big chances per game',
       'Big chances missed per game', 'Total shots per game',
       'Shots on target per game', 'Shots off target per game',
       'Succ. dribbles per game', 'Corners per game', 'Hit woodwork',
       'Counter attacks', 'Ball possession', 'Clean sheets',
       'Goals conceded per game', 'Tackles per game', 'Interceptions per game',
       'Clearances per game', 'Saves per game', 'Errors leading to shot',
       'Errors leading to goal', 'Penalties committed',
       'Penalty goals conceded', 'Clearance off line', 'Last man tackle',
       'Possession lost per game', 'Offsides per game', 'Fouls per game',
       'Yellow cards per game', 'Red cards', 'Penalty goals_total',
       'Penalty goals_acertados', 'Penalty goals_acuracia',
       'Free kick goals_total', 'Free kick goals_acertados',
       'Free kick goals_acuracia', 'Goals from inside the box_total',
       'Goals from inside the box_acertados',
       'Goals from inside the box_acuracia',
       'Goals from outside the box_total',
       'Goals from outside the box_acertados',
       'Goals from outside the box_acuracia', 'Accurate per game_total',
       'Accurate per game_acertados', 'Accurate per game_acuracia',
       'Acc. own half_total', 'Acc. own half_acertados',
       'Acc. own half_acuracia', 'Acc. opposition half_total',
       'Acc. opposition half_acertados', 'Acc. opposition half_acuracia',
       'Acc. long balls_total', 'Acc. long balls_acertados',
       'Acc. long balls_acuracia', 'Acc. crosses_total',
       'Acc. crosses_acertados', 'Acc. crosses_acuracia',
       'Duels won per game_total', 'Duels won per game_acertados',
       'Duels won per game_acuracia', 'Ground duels won_total',
       'Ground duels won_acertados', 'Ground duels won_acuracia',
       'Aerial duels won_total', 'Aerial duels won_acertados',
       'Aerial duels won_acuracia']]

df_sofascore.to_excel(f"sofascore_bruto/sofascore_bruto{rodada}.xlsx", index = None)

import json
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup

import os
import time

################################################################################################################################

